---
abstract: 'Dist::Zilla configuration the way ODYNIEC does it'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::pushd: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Path::Tiny: 0
  Test::DZil: 0
  Test::More: 0.96
  perl: 5.008001
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-ODYNIEC
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::PluginBundle::ODYNIEC:
    file: lib/Dist/Zilla/PluginBundle/ODYNIEC.pm
    version: 0.010
  Pod::Weaver::PluginBundle::ODYNIEC:
    file: lib/Pod/Weaver/PluginBundle/ODYNIEC.pm
    version: 0.010
requires:
  Dist::Zilla: 5
  Dist::Zilla::Plugin::Bugtracker: 1.110
  Dist::Zilla::Plugin::CPANFile: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::CheckMetaResources: 0.001
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0.002
  Dist::Zilla::Plugin::ContributorsFromGit: 0.004
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::GithubMeta: 0.36
  Dist::Zilla::Plugin::InsertCopyright: 0.001
  Dist::Zilla::Plugin::MetaNoIndex: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 1.14
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0.004
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::TaskWeaver: 0.101620
  Dist::Zilla::Plugin::Test::Compile: 2.036
  Dist::Zilla::Plugin::Test::MinimumVersion: 2.000003
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Plugin::Test::PodSpelling: 2.006001
  Dist::Zilla::Plugin::Test::Portability: 0
  Dist::Zilla::Plugin::Test::ReportPrereqs: 0.008
  Dist::Zilla::Plugin::Test::Version: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 1.121010
  Dist::Zilla::Role::PluginBundle::Config::Slicer: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Dist::Zilla::Role::PluginBundle::PluginRemover: 0
  Moose: 0.99
  Moose::Autobox: 0
  Pod::Elemental::Transformer::List: 0.101620
  Pod::Weaver: 4
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::Encoding: 0
  Pod::Weaver::Plugin::WikiDoc: 0
  Pod::Weaver::Section::Contributors: 0.001
  Pod::Weaver::Section::Support: 1.001
  Test::Portability::Files: 0.06
  autodie: 2.00
  namespace::autoclean: 0.09
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/odyniec/p5-Dist-Zilla-PluginBundle-ODYNIEC/issues
  homepage: https://github.com/odyniec/p5-Dist-Zilla-PluginBundle-ODYNIEC
  repository: https://github.com/odyniec/p5-Dist-Zilla-PluginBundle-ODYNIEC.git
version: 0.010
x_contributors:
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'Eric Johnson <eric.git@iijo.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Michal Wojciechowski <odyniec@odyniec.net>'
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
